name: t5_env
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - certifi=2024.8.30=py310h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.4.127=0
  - cuda-runtime=12.1.0=0
  - cudatoolkit=11.7.0=hd8887f6_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.12.1=h4a9f257_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py310heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py310h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=12.0.2.50=0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.10=py310h5eee18b_0
  - mkl_random=1.2.7=py310h1128e8f_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.2.1=py310h06a4308_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=10.4.0=py310h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.15=he870216_1
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py310h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py310h06a4308_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.2.0=py310_cu121
  - typing_extensions=4.11.0=py310h06a4308_0
  - urllib3=2.2.3=py310h06a4308_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==2.3.1
    - accelerate==1.12.0
    - aiohappyeyeballs==2.4.3
    - aiohttp==3.10.8
    - aiohttp-cors==0.7.0
    - aiosignal==1.3.1
    - airportsdata==20241001
    - alembic==1.15.1
    - annotated-types==0.7.0
    - anyio==4.8.0
    - astor==0.8.1
    - async-timeout==4.0.3
    - attrs==24.2.0
    - autoawq==0.2.8
    - backcall==0.2.0
    - bert-score==0.3.13
    - bitsandbytes==0.49.0
    - blake3==1.0.4
    - cachetools==5.5.1
    - captum==0.7.0
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - colorful==0.5.6
    - colorlog==6.9.0
    - compressed-tensors==0.9.0
    - contourpy==1.3.1
    - cut-cross-entropy==25.1.1
    - cycler==0.12.1
    - datasets==3.0.1
    - decorator==5.2.1
    - depyf==0.18.0
    - diffusers==0.32.2
    - dill==0.3.8
    - diskcache==5.6.3
    - distlib==0.3.9
    - distro==1.9.0
    - docker-pycreds==0.4.0
    - docstring-parser==0.16
    - einops==0.8.0
    - et-xmlfile==2.0.0
    - evaluate==0.4.3
    - exceptiongroup==1.2.2
    - fastapi==0.115.8
    - filelock==3.17.0
    - fonttools==4.56.0
    - frozenlist==1.4.1
    - fsspec==2024.6.1
    - gguf==0.10.0
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-api-core==2.24.1
    - google-auth==2.38.0
    - googleapis-common-protos==1.66.0
    - greenlet==3.1.1
    - grpcio==1.70.0
    - guidance==0.1.16
    - h11==0.14.0
    - hf-transfer==0.1.8
    - hf-xet==1.2.0
    - httpcore==1.0.7
    - httptools==0.6.4
    - httpx==0.28.1
    - huggingface-hub==0.36.0
    - imageio==2.37.0
    - importlib-metadata==8.6.1
    - iniconfig==2.0.0
    - interegular==0.3.3
    - ipython==7.34.0
    - jedi==0.19.2
    - jiter==0.8.2
    - joblib==1.4.2
    - json-repair==0.53.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - kiwisolver==1.4.8
    - lark==1.2.2
    - lazy-loader==0.4
    - lime==0.2.0.1
    - llvmlite==0.43.0
    - lm-format-enforcer==0.10.9
    - lxml==6.0.2
    - mako==1.3.9
    - markdown-it-py==3.0.0
    - matplotlib==3.10.1
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistral-common==1.5.2
    - msgpack==1.1.0
    - msgspec==0.19.0
    - multidict==6.1.0
    - multiprocess==0.70.16
    - nest-asyncio==1.6.0
    - nltk==3.9.2
    - numba==0.60.0
    - numpy==1.26.4
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-ml-py==12.570.86
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - openai==1.60.2
    - opencensus==0.11.4
    - opencensus-context==0.1.3
    - opencv-python-headless==4.11.0.86
    - openpyxl==3.1.5
    - optuna==4.2.1
    - ordered-set==4.1.0
    - outlines==0.1.11
    - outlines-core==0.1.26
    - packaging==24.1
    - pandas==2.2.3
    - parso==0.8.4
    - partial-json-parser==0.2.1.1.post5
    - peft==0.13.0
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - platformdirs==4.3.6
    - pluggy==1.5.0
    - portalocker==3.2.0
    - prometheus-client==0.21.1
    - prometheus-fastapi-instrumentator==7.0.2
    - prompt-toolkit==3.0.50
    - proto-plus==1.26.0
    - protobuf==3.20.3
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - py-cpuinfo==9.0.0
    - py-spy==0.4.0
    - pyairports==2.1.1
    - pyarrow==17.0.0
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybind11==2.13.6
    - pycountry==24.6.1
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pydpp==0.2.1
    - pygments==2.18.0
    - pyparsing==3.2.1
    - pytest==8.3.4
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.0.1
    - pytz==2024.2
    - pyzmq==26.2.1
    - ray==2.41.0
    - referencing==0.35.1
    - regex==2024.9.11
    - rich==13.9.2
    - rouge-score==0.1.2
    - rpds-py==0.20.0
    - rsa==4.9
    - sacrebleu==2.5.1
    - safetensors==0.4.5
    - scikit-image==0.25.2
    - scikit-learn==1.5.2
    - scipy==1.14.1
    - seaborn==0.13.2
    - sentence-transformers==4.1.0
    - sentencepiece==0.2.0
    - sentry-sdk==2.19.2
    - setproctitle==1.3.4
    - shap==0.48.0
    - shellingham==1.5.4
    - shtab==1.7.1
    - six==1.16.0
    - slicer==0.0.8
    - smart-open==7.1.0
    - smmap==5.0.1
    - sniffio==1.3.1
    - sqlalchemy==2.0.38
    - starlette==0.45.3
    - sympy==1.13.1
    - tabulate==0.9.0
    - threadpoolctl==3.5.0
    - tifffile==2025.5.10
    - tiktoken==0.7.0
    - tokenizers==0.19.1
    - tomli==2.2.1
    - torch==2.5.1
    - torchvision==0.20.1
    - tqdm==4.66.5
    - traitlets==5.14.3
    - transformers==4.49.0
    - transformers-interpret==0.10.0
    - triton==3.1.0
    - trl==0.11.1
    - typer-slim==0.20.0
    - typing-extensions==4.12.2
    - tyro==0.8.11
    - tzdata==2024.2
    - unsloth==2025.3.18
    - unsloth-zoo==2025.3.16
    - uvicorn==0.34.0
    - uvloop==0.21.0
    - virtualenv==20.29.1
    - vllm==0.7.0
    - wandb==0.19.0
    - watchfiles==1.0.4
    - wcwidth==0.2.13
    - websockets==14.2
    - wrapt==1.17.2
    - xformers==0.0.28.post3
    - xgrammar==0.1.11
    - xxhash==3.5.0
    - yarl==1.13.1
    - zipp==3.21.0
    - zstandard==0.23.0
prefix: /italian-hyperpartisan-neutralization/miniconda3/envs/t5_env
